# Generated by Django 2.1.2 on 2018-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181022_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=65, null=True)),
            ],
            options={
                'db_table': 'recs',
                'managed': False,
            },
        ),
    ]
